$("button").click(function() {
  let v1 = $("#v1").val();
  let v2 = $("#v2").val();
  let v3 = $("#v3").val();
  let v4 = $("#v4").val();
  let v5 = $("#v5").val();
  let v6 = $("#v6").val();
  let v7 = $("#v7").val();
  let v8 = $("#v8").val();
  let v9 = $("#v9").val();
  let v10 = $("#v10").val();
  let v11 = $("#v11").val();
  let v12 = $("#v12").val();
  let v13 = $("#v13").val();
  let v14 = $("#v14").val();
  let v15 = $("#v15").val();
  let v16 = $("#v16").val();
  let v17 = $("#v17").val();
  let v18 = $("#v18").val();
  let v19 = $("#v19").val();
  let v20 = $("#v20").val();
  let v21 = $("#v21").val();
  let v22 = $("#v22").val();
  let v23 = $("#v23").val();
  let v24 = $("#v24").val();
  let v25 = $("#v25").val();
  $("#text").text("I was "+v1+" (verb -ing) at the "+v2+" (noun that’s a place) the other day when I heard "+v3+" (holiday song) come on the radio. I was feeling really "+v4+" (adjective) and I’m pretty sure I looked super "+v5+" (adjective) because "+v6+" (your friend) walked in and almost "+v7+" (verb -ed). Seriously, she "+v8+" (verb -ed) for close to "+v9+" (amount of time)"+"This time every year I "+v10+" (verb) all the time because I get really exciting thinking about holiday "+v11+" (plural noun)! That’s why I was sitting at the "+v12+" (the place from up top) I was really hoping "+v13+" (a relative) would come by and give me at least "+v14+" (a number) pieces of holiday "+v15+" (food item)"+"That didn’t happen, but suddenly "+v16+" (a relative) "+v17+" (verb -ed) by in a huge "+v18+" (noun) on wheels dressed up as "+v19+" (a singer). I know "+v20+" (adjective) things happen around the holidays, but this didn’t make any sense! I picked up the phone to call "+v21+" (a person), but the phone turned into a big pile of "+v22+" (a messy food) and dripped all the way down to my "+v23+" (a body part) "+"Then my alarm clock went off for about "+v24+" (amount of time). It was all a dream! I had a ton of "+v25+" (a holiday food) before I went to sleep. Maybe that’s what gave me the crazy dream!");
});